/**
* Auto-Generated and OVERWRITTEN --- DO NOT EDIT THIS FILE
*
* Edit the corresponding '*.def.h' in 'src/ui/components/'.
**/

#include "feed_rate_view.h"
#include "stdlib.h"
#include "string.h"
#include "ui/layout/lv_vfl.h"
#include "ui/layout/lv_views.h"
static const char *TAG = "feed_rate_view";
static void feed_rate_view__impl__start() {}
feed_rate_view_t *feed_rate_view_create(lv_obj_t *parent) {
  size_t self_sz = sizeof(feed_rate_view_t);
  feed_rate_view_t *self = malloc(self_sz);
  memset(self, 0, self_sz);
  lv_obj_t *__curr_parent = self->main = lv_obj_create(parent);
  lv_obj_set_style_outline_width(__curr_parent, 1, 0);
  lv_obj_set_style_outline_color(__curr_parent, lv_color_hex(0xffffff), 0);
  lv_obj_set_style_outline_opa(__curr_parent, LV_OPA_60, 0);
  ;
  do {
    lv_obj_t *_dv_current_widget = self->main;
    lv_style_selector_t _dv_current_selector = LV_PART_MAIN | LV_STATE_DEFAULT;
    __text_color(lv_color_white()) __width(lv_pct(50)) __height(lv_pct(50));
  } while (0);
  lv_obj_t *left_mid = lv_obj_create(__curr_parent);
  do {
    lv_obj_t *__curr_parent = left_mid;
    lv_obj_set_style_outline_width(left_mid, 1, 0);
    lv_obj_set_style_outline_color(left_mid, lv_color_hex(0xffffff), 0);
    lv_obj_set_style_outline_opa(left_mid, LV_OPA_60, 0);
    ;
    __max_client_area(left_mid);
    self->left_mid = left_mid;
    lv_obj_t *header_cont = lv_obj_create(__curr_parent);
    do {
      lv_obj_t *__curr_parent = header_cont;
      lv_obj_set_style_outline_width(header_cont, 1, 0);
      lv_obj_set_style_outline_color(header_cont, lv_color_hex(0xffffff), 0);
      lv_obj_set_style_outline_opa(header_cont, LV_OPA_60, 0);
      ;
      __max_client_area(header_cont);
      self->header_cont = header_cont;
      lv_obj_t *caption = lv_label_create(__curr_parent);
      do {
        lv_obj_t *__curr_parent = caption;
        lv_obj_set_style_outline_width(caption, 1, 0);
        lv_obj_set_style_outline_color(caption, lv_color_hex(0xffffff), 0);
        lv_obj_set_style_outline_opa(caption, LV_OPA_60, 0);
        ;
        __max_client_area(caption);
        do {
          lv_obj_t *_dv_current_widget = caption;
          lv_style_selector_t _dv_current_selector =
              LV_PART_MAIN | LV_STATE_DEFAULT;
          __text("SNEEED") __max_client_area();
        } while (0);
        ;
      } while (0);
      self->caption = caption;
      ;
    } while (0);
    __size(header_cont, lv_pct(100), lv_pct(100));
    lv_obj_t *main_cont = lv_obj_create(__curr_parent);
    do {
      lv_obj_t *__curr_parent = main_cont;
      lv_obj_set_style_outline_width(main_cont, 1, 0);
      lv_obj_set_style_outline_color(main_cont, lv_color_hex(0xffffff), 0);
      lv_obj_set_style_outline_opa(main_cont, LV_OPA_60, 0);
      ;
      __max_client_area(main_cont);
      self->main_cont = main_cont;
      lv_obj_t *identifier = lv_label_create(__curr_parent);
      do {
        lv_obj_t *__curr_parent = identifier;
        lv_obj_set_style_outline_width(identifier, 1, 0);
        lv_obj_set_style_outline_color(identifier, lv_color_hex(0xffffff), 0);
        lv_obj_set_style_outline_opa(identifier, LV_OPA_60, 0);
        ;
        __max_client_area(identifier);
        do {
          lv_obj_t *_dv_current_widget = identifier;
          lv_style_selector_t _dv_current_selector =
              LV_PART_MAIN | LV_STATE_DEFAULT;
          __text("F") __max_client_area() __text_font(&lv_font_montserrat_24);
        } while (0);
        ;
      } while (0);
      self->identifier = identifier;
      lv_obj_t *value = lv_label_create(__curr_parent);
      do {
        lv_obj_t *__curr_parent = value;
        lv_obj_set_style_outline_width(value, 1, 0);
        lv_obj_set_style_outline_color(value, lv_color_hex(0xffffff), 0);
        lv_obj_set_style_outline_opa(value, LV_OPA_60, 0);
        ;
        __max_client_area(value);
        do {
          lv_obj_t *_dv_current_widget = value;
          lv_style_selector_t _dv_current_selector =
              LV_PART_MAIN | LV_STATE_DEFAULT;
          __text("7000") __max_client_area() __text_font(&lv_font_montserrat_24)
              __size(lv_pct(100), 40);
        } while (0);
        ;
      } while (0);
      self->value = value;
      lv_obj_t *spacer_left = lv_obj_create(__curr_parent);
      do {
        lv_obj_t *__curr_parent = spacer_left;
        lv_obj_set_style_outline_width(spacer_left, 1, 0);
        lv_obj_set_style_outline_color(spacer_left, lv_color_hex(0xffffff), 0);
        lv_obj_set_style_outline_opa(spacer_left, LV_OPA_60, 0);
        ;
        __max_client_area(spacer_left);
        do {
          lv_obj_t *_dv_current_widget = spacer_left;
          lv_style_selector_t _dv_current_selector =
              LV_PART_MAIN | LV_STATE_DEFAULT;
          __max_client_area() __bg_opa(LV_OPA_0) __border_width(0);
        } while (0);
        ;
      } while (0);
      self->spacer_left = spacer_left;
      lv_obj_t *bars = lv_obj_create(__curr_parent);
      do {
        lv_obj_t *__curr_parent = bars;
        lv_obj_set_style_outline_width(bars, 1, 0);
        lv_obj_set_style_outline_color(bars, lv_color_hex(0xffffff), 0);
        lv_obj_set_style_outline_opa(bars, LV_OPA_60, 0);
        ;
        __max_client_area(bars);
        self->bars = bars;
        do {
          lv_obj_t *_dv_current_widget = bars;
          lv_style_selector_t _dv_current_selector =
              LV_PART_MAIN | LV_STATE_DEFAULT;
          __pad_left(10) __pad_right(10);
        } while (0);
        lv_obj_t *feed_bar = lv_bar_create(__curr_parent);
        do {
          lv_obj_t *__curr_parent = feed_bar;
          lv_obj_set_style_outline_width(feed_bar, 1, 0);
          lv_obj_set_style_outline_color(feed_bar, lv_color_hex(0xffffff), 0);
          lv_obj_set_style_outline_opa(feed_bar, LV_OPA_60, 0);
          ;
          __max_client_area(feed_bar);
          do {
            lv_obj_t *_dv_current_widget = feed_bar;
            lv_style_selector_t _dv_current_selector =
                LV_PART_MAIN | LV_STATE_DEFAULT;
            __min_height(20) lv_bar_set_range(feed_bar, 0, 10000);
            lv_bar_set_value(feed_bar, 7000, LV_ANIM_OFF);
            ;
          } while (0);
          ;
        } while (0);
        self->feed_bar = feed_bar;
        lv_obj_t *feed_scale = lv_scale_create(__curr_parent);
        do {
          lv_obj_t *__curr_parent = feed_scale;
          lv_obj_set_style_outline_width(feed_scale, 1, 0);
          lv_obj_set_style_outline_color(feed_scale, lv_color_hex(0xffffff), 0);
          lv_obj_set_style_outline_opa(feed_scale, LV_OPA_60, 0);
          ;
          __max_client_area(feed_scale);
          do {
            lv_obj_t *_dv_current_widget = feed_scale;
            lv_style_selector_t _dv_current_selector =
                LV_PART_MAIN | LV_STATE_DEFAULT;
            __min_height(10)
                lv_scale_set_mode(feed_scale, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
            lv_scale_set_major_tick_every(feed_scale, 2);
            lv_scale_set_range(feed_scale, 0, 10);
            ;
          } while (0);
          ;
        } while (0);
        self->feed_scale = feed_scale;
        do {
          lv_obj_t *_dv_current_widget = bars;
          lv_style_selector_t _dv_current_selector =
              LV_PART_MAIN | LV_STATE_DEFAULT;
          __max_client_area();
        } while (0);
        ;
      } while (0);
      __size(bars, lv_pct(100), lv_pct(100));
      ;
    } while (0);
    __size(main_cont, lv_pct(100), lv_pct(100));
    ;
  } while (0);
  __size(left_mid, lv_pct(100), lv_pct(100));
  lv_obj_t *right = lv_obj_create(__curr_parent);
  do {
    lv_obj_t *__curr_parent = right;
    lv_obj_set_style_outline_width(right, 1, 0);
    lv_obj_set_style_outline_color(right, lv_color_hex(0xffffff), 0);
    lv_obj_set_style_outline_opa(right, LV_OPA_60, 0);
    ;
    __max_client_area(right);
    self->right = right;
    lv_obj_t *unit = lv_label_create(__curr_parent);
    do {
      lv_obj_t *__curr_parent = unit;
      lv_obj_set_style_outline_width(unit, 1, 0);
      lv_obj_set_style_outline_color(unit, lv_color_hex(0xffffff), 0);
      lv_obj_set_style_outline_opa(unit, LV_OPA_60, 0);
      ;
      __max_client_area(unit);
      do {
        lv_obj_t *_dv_current_widget = unit;
        lv_style_selector_t _dv_current_selector =
            LV_PART_MAIN | LV_STATE_DEFAULT;
        __text("MM/MIN") __bg_color(lv_color_hex(0xff00ff))
            __bg_opa(LV_OPA_100);
      } while (0);
      ;
    } while (0);
    self->unit = unit;
    lv_obj_t *override_lbl = lv_label_create(__curr_parent);
    do {
      lv_obj_t *__curr_parent = override_lbl;
      lv_obj_set_style_outline_width(override_lbl, 1, 0);
      lv_obj_set_style_outline_color(override_lbl, lv_color_hex(0xffffff), 0);
      lv_obj_set_style_outline_opa(override_lbl, LV_OPA_60, 0);
      ;
      __max_client_area(override_lbl);
      do {
        lv_obj_t *_dv_current_widget = override_lbl;
        lv_style_selector_t _dv_current_selector =
            LV_PART_MAIN | LV_STATE_DEFAULT;
        __text("Override");
      } while (0);
      ;
    } while (0);
    self->override_lbl = override_lbl;
    lv_obj_t *override = lv_label_create(__curr_parent);
    do {
      lv_obj_t *__curr_parent = override;
      lv_obj_set_style_outline_width(override, 1, 0);
      lv_obj_set_style_outline_color(override, lv_color_hex(0xffffff), 0);
      lv_obj_set_style_outline_opa(override, LV_OPA_60, 0);
      ;
      __max_client_area(override);
      do {
        lv_obj_t *_dv_current_widget = override;
        lv_style_selector_t _dv_current_selector =
            LV_PART_MAIN | LV_STATE_DEFAULT;
        __text("100%");
      } while (0);
      ;
    } while (0);
    self->override = override;
    lv_obj_t *load_lbl = lv_label_create(__curr_parent);
    do {
      lv_obj_t *__curr_parent = load_lbl;
      lv_obj_set_style_outline_width(load_lbl, 1, 0);
      lv_obj_set_style_outline_color(load_lbl, lv_color_hex(0xffffff), 0);
      lv_obj_set_style_outline_opa(load_lbl, LV_OPA_60, 0);
      ;
      __max_client_area(load_lbl);
      do {
        lv_obj_t *_dv_current_widget = load_lbl;
        lv_style_selector_t _dv_current_selector =
            LV_PART_MAIN | LV_STATE_DEFAULT;
        __text("Load");
      } while (0);
      ;
    } while (0);
    self->load_lbl = load_lbl;
    lv_obj_t *load = lv_label_create(__curr_parent);
    do {
      lv_obj_t *__curr_parent = load;
      lv_obj_set_style_outline_width(load, 1, 0);
      lv_obj_set_style_outline_color(load, lv_color_hex(0xffffff), 0);
      lv_obj_set_style_outline_opa(load, LV_OPA_60, 0);
      ;
      __max_client_area(load);
      do {
        lv_obj_t *_dv_current_widget = load;
        lv_style_selector_t _dv_current_selector =
            LV_PART_MAIN | LV_STATE_DEFAULT;
        __text("70%");
      } while (0);
      ;
    } while (0);
    self->load = load;
    ;
  } while (0);
  __size(right, lv_pct(100), lv_pct(100));
  _layout_grid(
      self->main_cont, _rows(LV_GRID_CONTENT, LV_GRID_FR(1)),
      _cols(LV_GRID_CONTENT, LV_GRID_CONTENT), _cell(self->identifier, 0, 0),
      _cell(self->value, 1, 0), _cell(self->bars, 1, 1),
      do {
        lv_obj_t *_dv_current_widget = self->main_cont;
        lv_style_selector_t _dv_current_selector =
            LV_PART_MAIN | LV_STATE_DEFAULT;
        __max_client_area() __height(lv_pct(100)) __bg_opa(LV_OPA_0);
      } while (0);
      ,
      do {
        lv_obj_t *_dv_current_widget = self->identifier;
        lv_style_selector_t _dv_current_selector =
            LV_PART_MAIN | LV_STATE_DEFAULT;
        __bg_opa(LV_OPA_0);
      } while (0);
      ,
      do {
        lv_obj_t *_dv_current_widget = self->value;
        lv_style_selector_t _dv_current_selector =
            LV_PART_MAIN | LV_STATE_DEFAULT;
        __min_width(lv_pct(50));
      } while (0);
      ,
      do {
        lv_obj_t *_dv_current_widget = self->bars;
        lv_style_selector_t _dv_current_selector =
            LV_PART_MAIN | LV_STATE_DEFAULT;
        __bg_opa(LV_OPA_0) __min_width(20) __min_height(30);
      } while (0);
      ,
      do {
        lv_obj_t *_dv_current_widget = self->spacer_left;
        lv_style_selector_t _dv_current_selector =
            LV_PART_MAIN | LV_STATE_DEFAULT;
        __size(10, 10);
      } while (0);) _layout_v(self->bars, LV_FLEX_ALIGN_START,
                              _sized(self->feed_bar, lv_pct(100), 30),
                              _sized(self->feed_scale, lv_pct(100), 10))
      _layout_v(
          self->right, LV_FLEX_ALIGN_START, _content(self->unit),
          _content(self->override_lbl), _content(self->override),
          _content(self->load_lbl), _content(self->load),
          do {
            lv_obj_t *_dv_current_widget = self->right;
            lv_style_selector_t _dv_current_selector =
                LV_PART_MAIN | LV_STATE_DEFAULT;
            __size(LV_SIZE_CONTENT, LV_SIZE_CONTENT);
          } while (0);
          ,
          do {
            lv_obj_t *_dv_current_widget = self->unit;
            lv_style_selector_t _dv_current_selector =
                LV_PART_MAIN | LV_STATE_DEFAULT;
            __width(LV_SIZE_CONTENT);
          } while (0);
          ;)
          _layout_v(
              self->left_mid, LV_FLEX_ALIGN_START, _content(self->header_cont),
              _flex(self->main_cont, 1),
              do {
                lv_obj_t *_dv_current_widget = self->left_mid;
                lv_style_selector_t _dv_current_selector =
                    LV_PART_MAIN | LV_STATE_DEFAULT;
                __bg_opa(LV_OPA_0);
              } while (0);)
              _layout_grid(self->main, _rows(LV_GRID_FR(1), LV_GRID_CONTENT),
                           _cols(LV_GRID_CONTENT), _cell(self->left_mid, 0, 0),
                           _cell(self->right, 1, 0), );
  ;
  return self;
};
