/**
* Auto-Generated and OVERWRITTEN --- DO NOT EDIT THIS FILE
*
* Edit the corresponding '*.def.h' in 'src/ui/components/'.
**/

#include "lvgl.h"
struct feed_rate_view_t {
  lv_obj_t *main;
  lv_obj_t *left_mid;
  lv_obj_t *header_cont;
  lv_obj_t *caption;
  lv_obj_t *main_cont;
  lv_obj_t *identifier;
  lv_obj_t *value;
  lv_obj_t *spacer_left;
  lv_obj_t *bars;
  lv_obj_t *feed_bar;
  lv_obj_t *feed_scale;
  lv_obj_t *right;
  lv_obj_t *unit;
  lv_obj_t *override_lbl;
  lv_obj_t *override;
  lv_obj_t *load;
  ;
};
typedef struct feed_rate_view_t feed_rate_view_t;
feed_rate_view_t *feed_rate_view_create(lv_obj_t *parent);
;
