// Generated by generate_ui_builder.py - DO NOT EDIT

#include "ui_builder.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "cJSON.h"

// --- Internal ID Mapping (JSON ID -> lv_obj_t* / lv_style_t*) ---
typedef struct IdMapEntry {
    const char *json_id;
    void *lv_ptr;
    struct IdMapEntry *next;
} IdMapEntry_t;

static void id_map_add(IdMapEntry_t **head, const char *json_id, void *lv_ptr) {
    if (!json_id || !lv_ptr) return;
    IdMapEntry_t *new_entry = (IdMapEntry_t *)malloc(sizeof(IdMapEntry_t));
    if (!new_entry) return; // Handle allocation failure
    new_entry->json_id = json_id; // cJSON string, owned by cJSON object
    new_entry->lv_ptr = lv_ptr;
    new_entry->next = *head;
    *head = new_entry;
}

static void* id_map_find(IdMapEntry_t *head, const char *json_id) {
    if (!json_id) return NULL;
    IdMapEntry_t *current = head;
    while (current) {
        if (strcmp(current->json_id, json_id) == 0) {
            return current->lv_ptr;
        }
        current = current->next;
    }
    return NULL;
}

static void id_map_free(IdMapEntry_t **head) {
    IdMapEntry_t *current = *head;
    while (current) {
        IdMapEntry_t *next = current->next;
        // Don't free json_id (owned by cJSON), don't free lv_ptr (owned by LVGL)
        free(current);
        current = next;
    }
    *head = NULL;
}

// --- Helper Functions ---
static lv_color_t parse_color_string(const char *color_str) {
    if (!color_str || color_str[0] != '#' || strlen(color_str) != 7) {
        return lv_color_black(); // Default or error color
    }
    long color_val = strtol(color_str + 1, NULL, 16);
    return lv_color_hex((uint32_t)color_val);
}

bool ui_builder_load_json(lv_obj_t *parent, const char *json_string, ui_builder_registry_lookup_cb lookup_func, void *user_data) {
    if (!parent || !json_string || !lookup_func) {
        return false;
    }

    cJSON *root = cJSON_Parse(json_string);
    if (!root) {
        const char *error_ptr = cJSON_GetErrorPtr();
        if (error_ptr != NULL) {
            fprintf(stderr, "Error parsing JSON before: %s\n", error_ptr);
        }
        return false;
    }

    cJSON *j_objects = cJSON_GetObjectItemCaseSensitive(root, "objects");
    cJSON *j_styles = cJSON_GetObjectItemCaseSensitive(root, "styles");
    bool success = false; // Assume failure until proven otherwise

    IdMapEntry_t *obj_id_map = NULL;
    IdMapEntry_t *style_id_map = NULL;

    // --- 1. Create Styles ---
    if (cJSON_IsObject(j_styles)) {
        cJSON *j_style = NULL;
        cJSON_ArrayForEach(j_style, j_styles) {
            const char *style_id = j_style->string;
            if (!style_id) continue;
            // Allocate style data on the heap, as LVGL might store pointers to them
            lv_style_t *new_style = (lv_style_t*)malloc(sizeof(lv_style_t));
            if (!new_style) {
                 fprintf(stderr, "Failed to allocate memory for style %s\n", style_id);
                 goto cleanup; // Allocation failed
            }
            lv_style_init(new_style);
            id_map_add(&style_id_map, style_id, new_style);
        }
    }

    // --- 2. Create Objects (Widgets) ---
    if (cJSON_IsObject(j_objects)) {
        cJSON *j_obj = NULL;
        cJSON_ArrayForEach(j_obj, j_objects) {
            const char *obj_id = j_obj->string;
            if (!obj_id) continue;

            cJSON *j_type = cJSON_GetObjectItemCaseSensitive(j_obj, "type");
            cJSON *j_parent = cJSON_GetObjectItemCaseSensitive(j_obj, "parent");

            if (!cJSON_IsString(j_type) || !j_type->valuestring) continue;
            const char *type_str = j_type->valuestring;

            lv_obj_t *parent_obj = parent; // Default to the main parent
            if (cJSON_IsString(j_parent) && j_parent->valuestring) {
                parent_obj = (lv_obj_t*)id_map_find(obj_id_map, j_parent->valuestring);
                if (!parent_obj) {
                    fprintf(stderr, "Warning: Parent object '%s' not found for object '%s'\n", j_parent->valuestring, obj_id);
                    parent_obj = parent; // Fallback to main parent
                }
            }

            lv_obj_t *new_obj = NULL;
            // --- Widget Creation Dispatcher ---
            if (strcmp(type_str, "lv_obj_create") == 0) {
                new_obj = lv_obj_create(parent_obj);
            }
            else if (strcmp(type_str, "lv_label_create") == 0) {
                new_obj = lv_label_create(parent_obj);
            }
            else {
                fprintf(stderr, "Warning: Unsupported widget type: %s\n", type_str);
                // Fallback: Create a basic lv_obj_t
                new_obj = lv_obj_create(parent_obj);
            }

            if (new_obj) {
                id_map_add(&obj_id_map, obj_id, new_obj);
            } else {
                 fprintf(stderr, "Failed to create object %s of type %s\n", obj_id, type_str);
                 goto cleanup; // Critical failure
            }
        }
    }

    // --- 3. Apply Style Properties ---
    if (cJSON_IsObject(j_styles)) {
        cJSON *j_style = NULL;
        cJSON_ArrayForEach(j_style, j_styles) {
            const char *style_id = j_style->string;
            lv_style_t *style_ptr = (lv_style_t*)id_map_find(style_id_map, style_id);
            if (!style_ptr) continue;

            cJSON *j_props = cJSON_GetObjectItemCaseSensitive(j_style, "properties");
            if (cJSON_IsObject(j_props)) {
                cJSON *j_prop = NULL;
                cJSON_ArrayForEach(j_prop, j_props) {
                    const char *prop_name = j_prop->string;
                    if (!prop_name) continue;

                    // --- Style Property Setter Dispatcher ---
                    if (strcmp(prop_name, "prop") == 0) {
                        // TODO: Handle style property type 'lv_style_value_t' for 'prop'
                    }
                    else if (strcmp(prop_name, "width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_width(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "min_width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_min_width(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "max_width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_max_width(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "height") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_height(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "min_height") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_min_height(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "max_height") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_max_height(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "length") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_length(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "x") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_x(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "y") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_y(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "align") == 0) {
                        // TODO: Handle style property type 'lv_align_t' for 'align'
                    }
                    else if (strcmp(prop_name, "transform_width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_transform_width(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "transform_height") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_transform_height(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "translate_x") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_translate_x(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "translate_y") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_translate_y(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "translate_radial") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_translate_radial(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "transform_scale_x") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_transform_scale_x(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "transform_scale_y") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_transform_scale_y(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "transform_rotation") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_transform_rotation(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "transform_pivot_x") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_transform_pivot_x(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "transform_pivot_y") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_transform_pivot_y(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "transform_skew_x") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_transform_skew_x(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "transform_skew_y") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_transform_skew_y(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "pad_top") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_pad_top(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "pad_bottom") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_pad_bottom(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "pad_left") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_pad_left(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "pad_right") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_pad_right(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "pad_row") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_pad_row(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "pad_column") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_pad_column(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "pad_radial") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_pad_radial(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "margin_top") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_margin_top(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "margin_bottom") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_margin_bottom(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "margin_left") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_margin_left(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "margin_right") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_margin_right(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "bg_color") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_bg_color(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "bg_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_bg_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "bg_grad_color") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_bg_grad_color(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "bg_grad_dir") == 0) {
                        // TODO: Handle style property type 'lv_grad_dir_t' for 'bg_grad_dir'
                    }
                    else if (strcmp(prop_name, "bg_main_stop") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_bg_main_stop(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "bg_grad_stop") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_bg_grad_stop(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "bg_main_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_bg_main_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "bg_grad_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_bg_grad_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "bg_grad") == 0) {
                        // TODO: Handle style property type 'const lv_grad_dsc_t *' for 'bg_grad'
                    }
                    else if (strcmp(prop_name, "bg_image_src") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            const void* ptr = lookup_func(j_prop->valuestring, user_data);
                            if (ptr) {
                                lv_style_set_bg_image_src(style_ptr, (const void *)ptr);
                            } else {
                                fprintf(stderr, "Warning: Named pointer '%s' not found for style property '%s'\n", j_prop->valuestring, prop_name);
                            }
                        }
                    }
                    else if (strcmp(prop_name, "bg_image_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_bg_image_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "bg_image_recolor") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_bg_image_recolor(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "bg_image_recolor_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_bg_image_recolor_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "bg_image_tiled") == 0) {
                        if (cJSON_IsBool(j_prop)) {
                            lv_style_set_bg_image_tiled(style_ptr, cJSON_IsTrue(j_prop) ? true : false);
                        }
                    }
                    else if (strcmp(prop_name, "border_color") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_border_color(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "border_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_border_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "border_width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_border_width(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "border_side") == 0) {
                        // TODO: Handle style property type 'lv_border_side_t' for 'border_side'
                    }
                    else if (strcmp(prop_name, "border_post") == 0) {
                        if (cJSON_IsBool(j_prop)) {
                            lv_style_set_border_post(style_ptr, cJSON_IsTrue(j_prop) ? true : false);
                        }
                    }
                    else if (strcmp(prop_name, "outline_width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_outline_width(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "outline_color") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_outline_color(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "outline_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_outline_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "outline_pad") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_outline_pad(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "shadow_width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_shadow_width(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "shadow_offset_x") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_shadow_offset_x(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "shadow_offset_y") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_shadow_offset_y(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "shadow_spread") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_shadow_spread(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "shadow_color") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_shadow_color(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "shadow_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_shadow_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "image_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_image_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "image_recolor") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_image_recolor(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "image_recolor_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_image_recolor_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "line_width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_line_width(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "line_dash_width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_line_dash_width(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "line_dash_gap") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_line_dash_gap(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "line_rounded") == 0) {
                        if (cJSON_IsBool(j_prop)) {
                            lv_style_set_line_rounded(style_ptr, cJSON_IsTrue(j_prop) ? true : false);
                        }
                    }
                    else if (strcmp(prop_name, "line_color") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_line_color(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "line_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_line_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "arc_width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_arc_width(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "arc_rounded") == 0) {
                        if (cJSON_IsBool(j_prop)) {
                            lv_style_set_arc_rounded(style_ptr, cJSON_IsTrue(j_prop) ? true : false);
                        }
                    }
                    else if (strcmp(prop_name, "arc_color") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_arc_color(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "arc_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_arc_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "arc_image_src") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            const void* ptr = lookup_func(j_prop->valuestring, user_data);
                            if (ptr) {
                                lv_style_set_arc_image_src(style_ptr, (const void *)ptr);
                            } else {
                                fprintf(stderr, "Warning: Named pointer '%s' not found for style property '%s'\n", j_prop->valuestring, prop_name);
                            }
                        }
                    }
                    else if (strcmp(prop_name, "text_color") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_text_color(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "text_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_text_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "text_font") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            const void* ptr = lookup_func(j_prop->valuestring, user_data);
                            if (ptr) {
                                lv_style_set_text_font(style_ptr, (const lv_font_t *)ptr);
                            } else {
                                fprintf(stderr, "Warning: Named pointer '%s' not found for style property '%s'\n", j_prop->valuestring, prop_name);
                            }
                        }
                    }
                    else if (strcmp(prop_name, "text_letter_space") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_text_letter_space(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "text_line_space") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_text_line_space(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "text_decor") == 0) {
                        // TODO: Handle style property type 'lv_text_decor_t' for 'text_decor'
                    }
                    else if (strcmp(prop_name, "text_align") == 0) {
                        // TODO: Handle style property type 'lv_text_align_t' for 'text_align'
                    }
                    else if (strcmp(prop_name, "text_outline_stroke_color") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_text_outline_stroke_color(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "text_outline_stroke_width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_text_outline_stroke_width(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "text_outline_stroke_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_text_outline_stroke_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "radius") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_radius(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "radial_offset") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_radial_offset(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "clip_corner") == 0) {
                        if (cJSON_IsBool(j_prop)) {
                            lv_style_set_clip_corner(style_ptr, cJSON_IsTrue(j_prop) ? true : false);
                        }
                    }
                    else if (strcmp(prop_name, "opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "opa_layered") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_opa_layered(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "color_filter_dsc") == 0) {
                        // TODO: Handle style property type 'const lv_color_filter_dsc_t *' for 'color_filter_dsc'
                    }
                    else if (strcmp(prop_name, "color_filter_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_color_filter_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "recolor") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_color_t color = parse_color_string(j_prop->valuestring);
                            lv_style_set_recolor(style_ptr, color);
                        }
                    }
                    else if (strcmp(prop_name, "recolor_opa") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_recolor_opa(style_ptr, (lv_opa_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "anim") == 0) {
                        // TODO: Handle style property type 'const lv_anim_t *' for 'anim'
                    }
                    else if (strcmp(prop_name, "anim_duration") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_anim_duration(style_ptr, (uint32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "transition") == 0) {
                        // TODO: Handle style property type 'const lv_style_transition_dsc_t *' for 'transition'
                    }
                    else if (strcmp(prop_name, "blend_mode") == 0) {
                        // TODO: Handle style property type 'lv_blend_mode_t' for 'blend_mode'
                    }
                    else if (strcmp(prop_name, "layout") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_layout(style_ptr, (uint16_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "base_dir") == 0) {
                        // TODO: Handle style property type 'lv_base_dir_t' for 'base_dir'
                    }
                    else if (strcmp(prop_name, "bitmap_mask_src") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            const void* ptr = lookup_func(j_prop->valuestring, user_data);
                            if (ptr) {
                                lv_style_set_bitmap_mask_src(style_ptr, (const void *)ptr);
                            } else {
                                fprintf(stderr, "Warning: Named pointer '%s' not found for style property '%s'\n", j_prop->valuestring, prop_name);
                            }
                        }
                    }
                    else if (strcmp(prop_name, "rotary_sensitivity") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_rotary_sensitivity(style_ptr, (uint32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "flex_flow") == 0) {
                        // TODO: Handle style property type 'lv_flex_flow_t' for 'flex_flow'
                    }
                    else if (strcmp(prop_name, "flex_main_place") == 0) {
                        // TODO: Handle style property type 'lv_flex_align_t' for 'flex_main_place'
                    }
                    else if (strcmp(prop_name, "flex_cross_place") == 0) {
                        // TODO: Handle style property type 'lv_flex_align_t' for 'flex_cross_place'
                    }
                    else if (strcmp(prop_name, "flex_track_place") == 0) {
                        // TODO: Handle style property type 'lv_flex_align_t' for 'flex_track_place'
                    }
                    else if (strcmp(prop_name, "flex_grow") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_flex_grow(style_ptr, (uint8_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "grid_column_dsc_array") == 0) {
                        // TODO: Handle style property type 'const int32_t *' for 'grid_column_dsc_array'
                    }
                    else if (strcmp(prop_name, "grid_column_align") == 0) {
                        // TODO: Handle style property type 'lv_grid_align_t' for 'grid_column_align'
                    }
                    else if (strcmp(prop_name, "grid_row_dsc_array") == 0) {
                        // TODO: Handle style property type 'const int32_t *' for 'grid_row_dsc_array'
                    }
                    else if (strcmp(prop_name, "grid_row_align") == 0) {
                        // TODO: Handle style property type 'lv_grid_align_t' for 'grid_row_align'
                    }
                    else if (strcmp(prop_name, "grid_cell_column_pos") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_grid_cell_column_pos(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "grid_cell_x_align") == 0) {
                        // TODO: Handle style property type 'lv_grid_align_t' for 'grid_cell_x_align'
                    }
                    else if (strcmp(prop_name, "grid_cell_column_span") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_grid_cell_column_span(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "grid_cell_row_pos") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_grid_cell_row_pos(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "grid_cell_y_align") == 0) {
                        // TODO: Handle style property type 'lv_grid_align_t' for 'grid_cell_y_align'
                    }
                    else if (strcmp(prop_name, "grid_cell_row_span") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_grid_cell_row_span(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "size") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_size(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "pad_all") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_pad_all(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "pad_hor") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_pad_hor(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "pad_ver") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_pad_ver(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "pad_gap") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_pad_gap(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "margin_hor") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_margin_hor(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "margin_ver") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_margin_ver(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "margin_all") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_margin_all(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "transform_scale") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_style_set_transform_scale(style_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else {
                        fprintf(stderr, "Warning: Unsupported style property: %s\n", prop_name);
                    }
                }
            }
        }
    }

    // --- 4. Apply Object Properties ---
    if (cJSON_IsObject(j_objects)) {
        cJSON *j_obj = NULL;
        cJSON_ArrayForEach(j_obj, j_objects) {
            const char *obj_id = j_obj->string;
            lv_obj_t *obj_ptr = (lv_obj_t*)id_map_find(obj_id_map, obj_id);
            if (!obj_ptr) continue;

            cJSON *j_props = cJSON_GetObjectItemCaseSensitive(j_obj, "properties");
            if (cJSON_IsObject(j_props)) {
                cJSON *j_prop = NULL;
                cJSON_ArrayForEach(j_prop, j_props) {
                    const char *prop_name = j_prop->string;
                    if (!prop_name) continue;

                     // --- Object Property Setter Dispatcher ---
                    if (strcmp(prop_name, "flex_flow") == 0) {
                        // TODO: Handle object property type 'lv_flex_flow_t' for 'flex_flow'
                    }
                    else if (strcmp(prop_name, "flex_align") == 0) {
                        // TODO: Handle object property type 'lv_flex_align_t' for 'flex_align'
                    }
                    else if (strcmp(prop_name, "flex_grow") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_flex_grow(obj_ptr, (uint8_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "grid_dsc_array") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_grid_dsc_array(obj_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "grid_align") == 0) {
                        // TODO: Handle object property type 'lv_grid_align_t' for 'grid_align'
                    }
                    else if (strcmp(prop_name, "grid_cell") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_grid_cell(obj_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "parent") == 0) {
                        // TODO: Handle object property type 'lv_obj_t *' for 'parent'
                    }
                    else if (strcmp(prop_name, "pos") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_pos(obj_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "x") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_x(obj_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "y") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_y(obj_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "size") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_size(obj_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_width(obj_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "height") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_height(obj_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "content_width") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_content_width(obj_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "content_height") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_content_height(obj_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "layout") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_layout(obj_ptr, (uint32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "align") == 0) {
                        // TODO: Handle object property type 'lv_align_t' for 'align'
                    }
                    else if (strcmp(prop_name, "transform") == 0) {
                        // TODO: Handle object property type 'const lv_matrix_t *' for 'transform'
                    }
                    else if (strcmp(prop_name, "ext_click_area") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_obj_set_ext_click_area(obj_ptr, (int32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "scrollbar_mode") == 0) {
                        // TODO: Handle object property type 'lv_scrollbar_mode_t' for 'scrollbar_mode'
                    }
                    else if (strcmp(prop_name, "scroll_dir") == 0) {
                        // TODO: Handle object property type 'lv_dir_t' for 'scroll_dir'
                    }
                    else if (strcmp(prop_name, "scroll_snap_x") == 0) {
                        // TODO: Handle object property type 'lv_scroll_snap_t' for 'scroll_snap_x'
                    }
                    else if (strcmp(prop_name, "scroll_snap_y") == 0) {
                        // TODO: Handle object property type 'lv_scroll_snap_t' for 'scroll_snap_y'
                    }
                    else if (strcmp(prop_name, "local_style_prop") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'local_style_prop'
                    }
                    else if (strcmp(prop_name, "style_width") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_width'
                    }
                    else if (strcmp(prop_name, "style_min_width") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_min_width'
                    }
                    else if (strcmp(prop_name, "style_max_width") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_max_width'
                    }
                    else if (strcmp(prop_name, "style_height") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_height'
                    }
                    else if (strcmp(prop_name, "style_min_height") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_min_height'
                    }
                    else if (strcmp(prop_name, "style_max_height") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_max_height'
                    }
                    else if (strcmp(prop_name, "style_length") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_length'
                    }
                    else if (strcmp(prop_name, "style_x") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_x'
                    }
                    else if (strcmp(prop_name, "style_y") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_y'
                    }
                    else if (strcmp(prop_name, "style_align") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_align'
                    }
                    else if (strcmp(prop_name, "style_transform_width") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_transform_width'
                    }
                    else if (strcmp(prop_name, "style_transform_height") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_transform_height'
                    }
                    else if (strcmp(prop_name, "style_translate_x") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_translate_x'
                    }
                    else if (strcmp(prop_name, "style_translate_y") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_translate_y'
                    }
                    else if (strcmp(prop_name, "style_translate_radial") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_translate_radial'
                    }
                    else if (strcmp(prop_name, "style_transform_scale_x") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_transform_scale_x'
                    }
                    else if (strcmp(prop_name, "style_transform_scale_y") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_transform_scale_y'
                    }
                    else if (strcmp(prop_name, "style_transform_rotation") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_transform_rotation'
                    }
                    else if (strcmp(prop_name, "style_transform_pivot_x") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_transform_pivot_x'
                    }
                    else if (strcmp(prop_name, "style_transform_pivot_y") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_transform_pivot_y'
                    }
                    else if (strcmp(prop_name, "style_transform_skew_x") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_transform_skew_x'
                    }
                    else if (strcmp(prop_name, "style_transform_skew_y") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_transform_skew_y'
                    }
                    else if (strcmp(prop_name, "style_pad_top") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_pad_top'
                    }
                    else if (strcmp(prop_name, "style_pad_bottom") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_pad_bottom'
                    }
                    else if (strcmp(prop_name, "style_pad_left") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_pad_left'
                    }
                    else if (strcmp(prop_name, "style_pad_right") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_pad_right'
                    }
                    else if (strcmp(prop_name, "style_pad_row") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_pad_row'
                    }
                    else if (strcmp(prop_name, "style_pad_column") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_pad_column'
                    }
                    else if (strcmp(prop_name, "style_pad_radial") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_pad_radial'
                    }
                    else if (strcmp(prop_name, "style_margin_top") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_margin_top'
                    }
                    else if (strcmp(prop_name, "style_margin_bottom") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_margin_bottom'
                    }
                    else if (strcmp(prop_name, "style_margin_left") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_margin_left'
                    }
                    else if (strcmp(prop_name, "style_margin_right") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_margin_right'
                    }
                    else if (strcmp(prop_name, "style_bg_color") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_color'
                    }
                    else if (strcmp(prop_name, "style_bg_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_opa'
                    }
                    else if (strcmp(prop_name, "style_bg_grad_color") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_grad_color'
                    }
                    else if (strcmp(prop_name, "style_bg_grad_dir") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_grad_dir'
                    }
                    else if (strcmp(prop_name, "style_bg_main_stop") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_main_stop'
                    }
                    else if (strcmp(prop_name, "style_bg_grad_stop") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_grad_stop'
                    }
                    else if (strcmp(prop_name, "style_bg_main_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_main_opa'
                    }
                    else if (strcmp(prop_name, "style_bg_grad_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_grad_opa'
                    }
                    else if (strcmp(prop_name, "style_bg_grad") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_grad'
                    }
                    else if (strcmp(prop_name, "style_bg_image_src") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_image_src'
                    }
                    else if (strcmp(prop_name, "style_bg_image_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_image_opa'
                    }
                    else if (strcmp(prop_name, "style_bg_image_recolor") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_image_recolor'
                    }
                    else if (strcmp(prop_name, "style_bg_image_recolor_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_image_recolor_opa'
                    }
                    else if (strcmp(prop_name, "style_bg_image_tiled") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bg_image_tiled'
                    }
                    else if (strcmp(prop_name, "style_border_color") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_border_color'
                    }
                    else if (strcmp(prop_name, "style_border_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_border_opa'
                    }
                    else if (strcmp(prop_name, "style_border_width") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_border_width'
                    }
                    else if (strcmp(prop_name, "style_border_side") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_border_side'
                    }
                    else if (strcmp(prop_name, "style_border_post") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_border_post'
                    }
                    else if (strcmp(prop_name, "style_outline_width") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_outline_width'
                    }
                    else if (strcmp(prop_name, "style_outline_color") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_outline_color'
                    }
                    else if (strcmp(prop_name, "style_outline_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_outline_opa'
                    }
                    else if (strcmp(prop_name, "style_outline_pad") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_outline_pad'
                    }
                    else if (strcmp(prop_name, "style_shadow_width") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_shadow_width'
                    }
                    else if (strcmp(prop_name, "style_shadow_offset_x") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_shadow_offset_x'
                    }
                    else if (strcmp(prop_name, "style_shadow_offset_y") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_shadow_offset_y'
                    }
                    else if (strcmp(prop_name, "style_shadow_spread") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_shadow_spread'
                    }
                    else if (strcmp(prop_name, "style_shadow_color") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_shadow_color'
                    }
                    else if (strcmp(prop_name, "style_shadow_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_shadow_opa'
                    }
                    else if (strcmp(prop_name, "style_image_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_image_opa'
                    }
                    else if (strcmp(prop_name, "style_image_recolor") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_image_recolor'
                    }
                    else if (strcmp(prop_name, "style_image_recolor_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_image_recolor_opa'
                    }
                    else if (strcmp(prop_name, "style_line_width") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_line_width'
                    }
                    else if (strcmp(prop_name, "style_line_dash_width") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_line_dash_width'
                    }
                    else if (strcmp(prop_name, "style_line_dash_gap") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_line_dash_gap'
                    }
                    else if (strcmp(prop_name, "style_line_rounded") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_line_rounded'
                    }
                    else if (strcmp(prop_name, "style_line_color") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_line_color'
                    }
                    else if (strcmp(prop_name, "style_line_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_line_opa'
                    }
                    else if (strcmp(prop_name, "style_arc_width") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_arc_width'
                    }
                    else if (strcmp(prop_name, "style_arc_rounded") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_arc_rounded'
                    }
                    else if (strcmp(prop_name, "style_arc_color") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_arc_color'
                    }
                    else if (strcmp(prop_name, "style_arc_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_arc_opa'
                    }
                    else if (strcmp(prop_name, "style_arc_image_src") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_arc_image_src'
                    }
                    else if (strcmp(prop_name, "style_text_color") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_text_color'
                    }
                    else if (strcmp(prop_name, "style_text_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_text_opa'
                    }
                    else if (strcmp(prop_name, "style_text_font") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_text_font'
                    }
                    else if (strcmp(prop_name, "style_text_letter_space") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_text_letter_space'
                    }
                    else if (strcmp(prop_name, "style_text_line_space") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_text_line_space'
                    }
                    else if (strcmp(prop_name, "style_text_decor") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_text_decor'
                    }
                    else if (strcmp(prop_name, "style_text_align") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_text_align'
                    }
                    else if (strcmp(prop_name, "style_text_outline_stroke_color") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_text_outline_stroke_color'
                    }
                    else if (strcmp(prop_name, "style_text_outline_stroke_width") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_text_outline_stroke_width'
                    }
                    else if (strcmp(prop_name, "style_text_outline_stroke_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_text_outline_stroke_opa'
                    }
                    else if (strcmp(prop_name, "style_radius") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_radius'
                    }
                    else if (strcmp(prop_name, "style_radial_offset") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_radial_offset'
                    }
                    else if (strcmp(prop_name, "style_clip_corner") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_clip_corner'
                    }
                    else if (strcmp(prop_name, "style_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_opa'
                    }
                    else if (strcmp(prop_name, "style_opa_layered") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_opa_layered'
                    }
                    else if (strcmp(prop_name, "style_color_filter_dsc") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_color_filter_dsc'
                    }
                    else if (strcmp(prop_name, "style_color_filter_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_color_filter_opa'
                    }
                    else if (strcmp(prop_name, "style_recolor") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_recolor'
                    }
                    else if (strcmp(prop_name, "style_recolor_opa") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_recolor_opa'
                    }
                    else if (strcmp(prop_name, "style_anim") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_anim'
                    }
                    else if (strcmp(prop_name, "style_anim_duration") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_anim_duration'
                    }
                    else if (strcmp(prop_name, "style_transition") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_transition'
                    }
                    else if (strcmp(prop_name, "style_blend_mode") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_blend_mode'
                    }
                    else if (strcmp(prop_name, "style_layout") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_layout'
                    }
                    else if (strcmp(prop_name, "style_base_dir") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_base_dir'
                    }
                    else if (strcmp(prop_name, "style_bitmap_mask_src") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_bitmap_mask_src'
                    }
                    else if (strcmp(prop_name, "style_rotary_sensitivity") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_rotary_sensitivity'
                    }
                    else if (strcmp(prop_name, "style_flex_flow") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_flex_flow'
                    }
                    else if (strcmp(prop_name, "style_flex_main_place") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_flex_main_place'
                    }
                    else if (strcmp(prop_name, "style_flex_cross_place") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_flex_cross_place'
                    }
                    else if (strcmp(prop_name, "style_flex_track_place") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_flex_track_place'
                    }
                    else if (strcmp(prop_name, "style_flex_grow") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_flex_grow'
                    }
                    else if (strcmp(prop_name, "style_grid_column_dsc_array") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_grid_column_dsc_array'
                    }
                    else if (strcmp(prop_name, "style_grid_column_align") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_grid_column_align'
                    }
                    else if (strcmp(prop_name, "style_grid_row_dsc_array") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_grid_row_dsc_array'
                    }
                    else if (strcmp(prop_name, "style_grid_row_align") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_grid_row_align'
                    }
                    else if (strcmp(prop_name, "style_grid_cell_column_pos") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_grid_cell_column_pos'
                    }
                    else if (strcmp(prop_name, "style_grid_cell_x_align") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_grid_cell_x_align'
                    }
                    else if (strcmp(prop_name, "style_grid_cell_column_span") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_grid_cell_column_span'
                    }
                    else if (strcmp(prop_name, "style_grid_cell_row_pos") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_grid_cell_row_pos'
                    }
                    else if (strcmp(prop_name, "style_grid_cell_y_align") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_grid_cell_y_align'
                    }
                    else if (strcmp(prop_name, "style_grid_cell_row_span") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_grid_cell_row_span'
                    }
                    else if (strcmp(prop_name, "style_pad_all") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_pad_all'
                    }
                    else if (strcmp(prop_name, "style_pad_hor") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_pad_hor'
                    }
                    else if (strcmp(prop_name, "style_pad_ver") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_pad_ver'
                    }
                    else if (strcmp(prop_name, "style_margin_all") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_margin_all'
                    }
                    else if (strcmp(prop_name, "style_margin_hor") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_margin_hor'
                    }
                    else if (strcmp(prop_name, "style_margin_ver") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_margin_ver'
                    }
                    else if (strcmp(prop_name, "style_pad_gap") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_pad_gap'
                    }
                    else if (strcmp(prop_name, "style_size") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_size'
                    }
                    else if (strcmp(prop_name, "style_transform_scale") == 0) {
                        // TODO: Handle object property type 'lv_style_selector_t' for 'style_transform_scale'
                    }
                    else if (strcmp(prop_name, "flag") == 0) {
                        if (cJSON_IsBool(j_prop)) {
                            lv_obj_set_flag(obj_ptr, cJSON_IsTrue(j_prop) ? true : false);
                        }
                    }
                    else if (strcmp(prop_name, "state") == 0) {
                        if (cJSON_IsBool(j_prop)) {
                            lv_obj_set_state(obj_ptr, cJSON_IsTrue(j_prop) ? true : false);
                        }
                    }
                    else if (strcmp(prop_name, "user_data") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            const void* ptr = lookup_func(j_prop->valuestring, user_data);
                            if (ptr) {
                                lv_obj_set_user_data(obj_ptr, (void *)ptr);
                            } else {
                                fprintf(stderr, "Warning: Named pointer '%s' not found for object property '%s'\n", j_prop->valuestring, prop_name);
                            }
                        }
                    }
                    else if (strcmp(prop_name, "id") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            const void* ptr = lookup_func(j_prop->valuestring, user_data);
                            if (ptr) {
                                lv_obj_set_id(obj_ptr, (void *)ptr);
                            } else {
                                fprintf(stderr, "Warning: Named pointer '%s' not found for object property '%s'\n", j_prop->valuestring, prop_name);
                            }
                        }
                    }
                    else if (strcmp(prop_name, "text") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_label_set_text(obj_ptr, j_prop->valuestring);
                        }
                    }
                    else if (strcmp(prop_name, "text_fmt") == 0) {
                        // TODO: Handle object property type 'ellipsis' for 'text_fmt'
                    }
                    else if (strcmp(prop_name, "text_static") == 0) {
                        if (cJSON_IsString(j_prop)) {
                            lv_label_set_text_static(obj_ptr, j_prop->valuestring);
                        }
                    }
                    else if (strcmp(prop_name, "long_mode") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_label_set_long_mode(obj_ptr, (lv_label_long_mode_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "text_selection_start") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_label_set_text_selection_start(obj_ptr, (uint32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "text_selection_end") == 0) {
                        if (cJSON_IsNumber(j_prop)) {
                            lv_label_set_text_selection_end(obj_ptr, (uint32_t)cJSON_GetNumberValue(j_prop));
                        }
                    }
                    else if (strcmp(prop_name, "recolor") == 0) {
                        if (cJSON_IsBool(j_prop)) {
                            lv_label_set_recolor(obj_ptr, cJSON_IsTrue(j_prop) ? true : false);
                        }
                    }
                    else {
                        fprintf(stderr, "Warning: Unsupported object property: %s\n", prop_name);
                    }
                }
            }

            // --- 5. Apply Styles to Object ---
            cJSON *j_obj_styles = cJSON_GetObjectItemCaseSensitive(j_obj, "styles");
            if (cJSON_IsObject(j_obj_styles)) {
                cJSON *j_part_styles = NULL;
                cJSON_ArrayForEach(j_part_styles, j_obj_styles) {
                    const char *part_key = j_part_styles->string; // e.g., "part_0"
                    if (!part_key || strncmp(part_key, "part_", 5) != 0) continue;
                    lv_part_t part_id = (lv_part_t)atoi(part_key + 5);

                    if (cJSON_IsArray(j_part_styles)) {
                        cJSON *j_style_id_item = NULL;
                        cJSON_ArrayForEach(j_style_id_item, j_part_styles) {
                            if (cJSON_IsString(j_style_id_item) && j_style_id_item->valuestring) {
                                const char *style_id_str = j_style_id_item->valuestring;
                                lv_style_t *style_ptr = (lv_style_t*)id_map_find(style_id_map, style_id_str);
                                if (style_ptr) {
                                    lv_obj_add_style(obj_ptr, style_ptr, part_id);
                                } else {
                                    fprintf(stderr, "Warning: Style '%s' not found when applying to object '%s' part %d\n", style_id_str, obj_id, (int)part_id);
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    success = true; // If we reached here without critical errors

cleanup:
    id_map_free(&obj_id_map);
    // IMPORTANT: Styles allocated with malloc need to be freed eventually!
    //            The caller needs a strategy for this. We free the map only.
    //            Consider adding a function `ui_builder_free_styles(style_map)`?
    id_map_free(&style_id_map); 
    cJSON_Delete(root);
    return success;
}
